### ISSUE TITLE
[Request] Can you make a version that will work with bookmarklet injection

### ISSUE THREAD

**Issue by G-xming** [DarkSnakeGang/GoogleSnakeModLoader#12]
Can you make a version that will work with bookmarklet injection

**Comment by hwatson381** [comment]
It would be very tricky to make something like that to work. There's an explanation here as to why we had to switch away from bookmarklets https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/why_not_bookmarks.md

**Comment by Patheticlol** [comment]
> Can you make a version that will work with bookmarklet injection

If you're too lazy to click the link
> # Why did we switch to userscripts? What happened to the bookmarks?

The bookmark method no longer works since the code of snake changed in a way that happens to prevent this.
We don't think that google did this because they wanted to make modding more difficult, but rather that this was an unintended side effect.

The short explanation for why bookmarks don't work is that we can't change the snake code whilst it is still running any more.
A userscript can get around this by running as soon as the website gets visited. It can then make alterations to the google snake code before it has had a chance to run.

The more complex explanation is as follows: 
The change that triggered this was that google moved all the snake code inside an immediately invoked function expression (IIFE). So the google snake code now looks like the below (javascript)

```js
this._s=this._s||{};
(function(_){
  var window=this;
  //All of google snake code goes here
})(this._s);
```

Previously we could override functions within the google snake code to make changes (e.g. overriding the function that sets the map size, to enable different map sizes).
This is now impossible to do from a bookmark.

By using userscripts we can now intercept the google snake script right at the start, make changes to this script and then run the code from this script.

**Comment by Patheticlol** [comment]
@hwatson381 I would like to ask, would a bookmarklet injection version work with an old version of google snake?

**Comment by hwatson381** [comment]
@Patheticlol The current mods are targeted at the newest version of snake, so they won't work on older versions. However, it is possible, although a little complicated, to run older versions of mods on older version of snake. See here for an example https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/issues/116

You would have to be careful with which older version of the mod you choose and which older version of snake you choose since these would need to line up.
