### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by awesomechapro** [DarkSnakeGang/GoogleSnakeModLoader#4]
The mod doesn't seem to be working for me. I see it does run whenever I open the snake window, but doesn't go any further. Any help? 
![image_2023-03-28_154851357](https://user-images.githubusercontent.com/114811027/228131180-583d36e8-2265-4edf-b708-2d44b2e95b8b.png)

**Comment by hwatson381** [comment]
Can you show what the indicator looks like?
![image](https://user-images.githubusercontent.com/69080709/228304319-e9184913-8ad6-480c-97f1-8b8afa58942d.png)

Have you tried on fbx snake? https://www.google.com/fbx?fbx=snake_arcade

https://discord.gg/tajxuKKjrT If you have discord, you could join here and make a post in tech-support channel.

**Comment by hwatson381** [comment]
Are you using the opera browser?

If so then you need to do some extra steps for enabling tampermonkey on search results pages.

https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/opera_extra_steps.md

**Comment by awesomechapro** [comment]
I have followed the extra steps for opera but it still doesn't seem to work, it just appears like regular google snake

**Comment by hwatson381** [comment]
Someone had a similar issue which was happening because they had slow internet.

https://github.com/DarkSnakeGang/GoogleSnakeModLoader/issues/5#issuecomment-1519115017

Could you try the steps in my reply here (telling the mod to run at document-body) and let me know if it makes a difference.

Another thing to try would be to update the modloader to the latest version https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/update_guide.md
